### ISSUE TITLE
Problemas con ejemplo de interrupts

### ISSUE THREAD

**Issue by Pabloski100** [IIC2343/Syllabus-2021-2-S1#35]
Hola, estaba viendo el ejemplo de interrups de la ayudantía y tengo un problema, a pesar de seguir exactamente los mismos pasos de la ayudantía no consigo el mismo comportamiento, conecto el timer tool, compilo el programa e inicio el timer tool, pero no me sale el mensaje cada 5 segundos, sino que se imprime continuamente, que podría causar ese problema?

**Comment by tocococa** [comment]
Hola, estás ejecutando el mismo código que subimos junto con la ayudantía? Y que versión de RARS estás usando?

**Comment by Pabloski100** [comment]
Si, el código que esta en los extras del repositorio, y uso el mismo RARS del repo, sale que es 1.5

**Comment by Mario-uc** [comment]
¿Lograron resolver esto? tengo el mismo problema :(

**Comment by RenatoVWS** [comment]
Hola! Me paso lo mismoo y todavia no lo resuelvo

**Comment by tocococa** [comment]
Hola, estaba probando el código de `interrupts.asm` con la misma versión del emulador que les subí en el repo de este semestre, y no logro reproducir el problema, a mi me imprime "Hola!" en intervalos que corresponden a los milisegundos descritos en el script, les puedo preguntar, en que sistema operativo están corriendo el emulador? Y están seguros que a) no lo están corriendo a velocidad reducida y b) tienen el timertool encendido y conectado al programa? El emulador es medio inestable para algunas cosas, y si tienen más de una pestaña abierta, puede que el timer se les esté activando en otra pesataña en lugar de la que tienen con el script que están usando.

Por favor dígname como les va con esto, para saber cómo seguir.

**Comment by RenatoVWS** [comment]
Hola! A mi se me resolvio, cerre el emulador y eché a andar denuevo el Timertools. Ahí me empezó a correr bien. Gracias!
