### ISSUE TITLE
Duda general tarea 2 

### ISSUE THREAD

**Issue by JuanmaGuzman** [IIC2343/Syllabus-2021-2-S1#36]
Hola buenas! Tengo dudas de cómo empezar la tarea, no sé si se busca que trabajemos todos los datos mediante manipulación de registros y funciones de jump como la tarea 1, y con esto simular políticas de escritura y funciones de correspondencia? O si hay que programar con funciones nuevas para simular algún tipo de cache RAM o memoria virtual? 
Saludooos

**Comment by tocococa** [comment]
Hola @JuanmaGuzman, la tarea es similar a la T1 en que tienen que programar/resolver lo que se les pide en assembly RISC-V. No es necesario que simules nada de memoria ni cachés, ya que esto es algo que no se ve directamente al nivel del assembler.
