### ISSUE TITLE
Convenciones respecto al almacenamiento de datos en el stack

### ISSUE THREAD

**Issue by MarceloSaldias** [IIC2343/Syllabus-2021-2-S1#37]
Hola!
En la ayudantía 6 vimos un ejemplo donde mostraban como se utilizan las interrupciones en RISC-V pero me queda una duda en lo que respecta al guardado de algunos registros temporales en el stack. Un extracto de `interrupts.asm`

   ```
 handle:
        # guardar temporales
        addi	sp, sp, -20
        sw	t0, 16(sp)
        sw	t1, 12(sp)
        sw	t2, 8(sp)
        sw	a0, 4(sp)
        sw	a7, 0(sp)
        
        # imprimimos hola!
        li	a7, 4
        la	a0, hello
        ecall
        
        # rearmar el timer para que dispare cada 5 segundos
        lw a0 timeNow
        lw t2 0(a0)
        li t1 5000
        add t1 t2 t1
        lw t0 cmp
        sw t1 0(t0)
        
        # recargar temorales y salir
        lw	t0, 16(sp)
        lw	t1, 12(sp)
        lw	t2, 8(sp)
        lw	a0, 4(sp)
        lw	a7, 0(sp)
        addi	sp, sp, 20	
        uret
```
Mi duda es si es realmente necesario guardar el valor de los registros temporales (t0, t1, t2) o forma parte de alguna convención en RISC-V? . Tenia entendido que al ser temporales y no estar siendo usados como parte de una subrutina anidada no era necesario mantener su valor original en el stack. 

**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**

**Comment by tocococa** [comment]
Hola @MarceloSaldias, efectivamente no es obligatorio almacenar el contenido de los registros `t*` cuando se trata de un llamado a una subrutina o proceso que es parte del flujo del programa, pero en este caso, se trata de una subrutina asociada a una interrupción, que puede ocurrir en cualquier momento, independiente de lo que sea que está haciendo el programa principal, por lo que es buena práctica respaldar todos los registros que se vayan a usar en la subrutina, para no provocar comportamiento indeterminado en la sección principal.
