### ISSUE TITLE
Duda respecto a la cantidad de participantes del viaje

### ISSUE THREAD

**Issue by ElKrra** [IIC2343/Syllabus-2021-2-S1#38]
Hola!

Leyendo el enunciado me surgió una duda y es que más que nada sobre el número máximo de participantes del viaje teniendo en cuenta que existe un número limitado de registros disponibles en el emulador. Hay un número máximo de participantes o efectivamente se debe hacer el programa pensando en n personas, en cuyo caso dicho número n puede ser muy grande?

Por otro lado, quería saber si subirán el template y los tests de esta tarea.

Saludos!

**Comment by rbhernandez** [comment]
Hola, el programa debe ser pensado para n personas. El template no lo vamos a subir, pero lo puedes copiar directamente del que aparece en el enunciado y los tests se subirán dentro de esta semana.

Saludos!
