### ISSUE TITLE
Duda comparación entre floats en RISC-V

### ISSUE THREAD

**Issue by burgosibarra** [IIC2343/Syllabus-2021-2-S1#39]
Hola!
¿Por qué el siguiente código termina con t0 = 1?
![issue](https://user-images.githubusercontent.com/53795389/139731513-665ccd66-8c2d-4c7c-b460-d34fbac075b7.PNG)

**Comment by tocococa** [comment]
Hola, a priori me parece que se trata de un bug con el emulador, pero voy a averiguar un poquito más y te doy una respuesta más completa. Creo que por la implementación que hay de Java por debajo esa comparación entre 0.0s no la maneja bien.

**Comment by burgosibarra** [comment]
Gracias! Por el momento ¿me recomendarías otra forma de comparar floats? Pensaba convertir los floats en unsigned integers y compararlos como integers cualquiera, pero no estoy muy seguro de eso

**Comment by tocococa** [comment]
Si estás revisando una condición `>`, puedes chequear el caso borde en que son iguales con `feq.s` y así si tienes 1 en ambos, sabes que `>` no se está cumpliendo y debiese ser 0.
