### ISSUE TITLE
Uso del exit2

### ISSUE THREAD

**Issue by Mario-uc** [IIC2343/Syllabus-2021-2-S1#40]
**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**

Buenas, tenía una consulta sobre el funcionamiento del ecall "exit2" , es decir se le ingresa un input a0 que es el valor con el que sale del programa, pero no entiendo como compara o con que compara para saber que al llegar a ese número sale del programa

**Comment by tocococa** [comment]
Hola,

La ecall `exit2` no hace que al ingresar un número x en a0 el programa salga, si no que al salir, sale retornando el número x, que en el contexto de un sistema operativo, podría ser utilizado para tomar alguna acción.
