### ISSUE TITLE
Duda ids amigues T2

### ISSUE THREAD

**Issue by fran-gl** [IIC2343/Syllabus-2021-2-S1#41]
Hola, me surgió una duda con respecto a los ids de los amigues de la T2. 
¿Estos siempre van a ser números enteros? Es decir, no puede haber, por ejemplo, un amigue con id 1.5 o sí? 

Como en .data se declaran con .word estoy asumiendo que efectivamente son solo números enteros, pero me quería asegurar.

Muchas gracias de antemano!

**Comment by rbhernandez** [comment]
Hola a ambos, tal como dicen: los ID siempre serán enteros porque son posiciones en un arreglo :)

**Comment by fran-gl** [comment]
Perfecto, muchas gracias!
