### ISSUE TITLE
Input P2

### ISSUE THREAD

**Issue by MGilB** [IIC2343/Syllabus-2021-2-S1#42]
**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**
Hola en la parte 2 los inputs van a ser siempre números enteros o pueden ser floats también?

**Comment by tocococa** [comment]
Hola,

En la P2, no hay dos inputs, solo se continua preguntando un tiempo cada vez que expira un timer, y en principio el valor ingresado sería un entero.

**Comment by galanfd** [comment]
¡Hola! Mi pregunta es: ¿Se puede asumir que siempre los inputs serán enteros? 
¿O para probar la excepción de errores debemos manejar en caso de que se ponga texto como input por ejemplo?

**Comment by tocococa** [comment]
@galanfd si quieres puedes manejar errores, pero es razonable asumir que el input va a ser un entero.

**Comment by galanfd** [comment]
@tocococa Perfecto! Muchísimas gracias!
