### ISSUE TITLE
Valor de registros en Operaciones

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2343/Syllabus-2021-2-S1#43]
Hola! Estoy trabajando en la P1 de la tarea 2 y estoy implementando el uso de arrays en risc-v.
Encontré en internet un ejemplo que pedía al Stack memoria extra para 10 números de la siguiente manera:

<img width="178" alt="Captura de Pantalla 2021-11-02 a la(s) 17 10 30" src="https://user-images.githubusercontent.com/48494298/139944905-77b900cf-0a1a-4034-a442-569c7e70c12c.png">

Mi pregunta viene en las lineas 4 y 8 donde escribe "sw s0, 40(sp) " y  " sw x18, -40(s0)"
La pregunta es cómo puedo escribir la misma oración pero en vez de un número definido "40(sp)" expresarlo mediante un el valor dentro de un registro. 
Esto de debido a que el largo de mi array es variable según la cantidad de amigos.

Intente escribir "sw s0, (a6)(sp)"  
Donde el valor dentro del registro a6 contiene la cantidad de amigos multiplicado por 4, pero el intérprete me tira error.

**Comment by tocococa** [comment]
Hola @JuanDlugo, en primer lugar, el stack se debiese comportar como una cola LIFO, por lo que no te recomiendo que uses el stack para almacenar tu arreglo.

Respecto a tu segunda consulta, si tienes una dirección en memoria para apuntar al final de un arreglo de largo variable, si tu dirección está en `a0`, por decir algo, puedes sumar el offset correspondiente a `a0` con `add a0, a0, a1`, suponiendo que en `a1` tienes el offset, y luego acceder a esa dirección con `0(a0)`.

**Comment by JuanDlugo** [comment]
Dale buenísimo, muchas gracias @tocococa !
