### ISSUE TITLE
Duda ayudantía 9, instrucciones CSR

### ISSUE THREAD

**Issue by JuanDlugo** [IIC2343/Syllabus-2021-2-S1#44]
Hola! 
Tengo una duda sobre la última ayudantía, más en especifico sobre que realiza un pedazo de código de la implementación con TIMER TOOL.
Quisiera pedir si por favor podrían explicar que realizan los siguientes comandos. 
Gracias!!

![Captura de Pantalla 2021-11-03 a la(s) 11 10 36](https://user-images.githubusercontent.com/48494298/140076452-484f2dd3-8069-43a9-8f6c-89c980bf6f1f.png)

**Comment by tocococa** [comment]
Hola! Las instrucciones `csr*` vienen de "Configuration Status Register", y son instrucciones especiales para modificar los registros encargados de las interrupciones. En particular, `csrrs rd, csr, rs1` (Atomic Read and Set Bits in CSR) se utiliza para setear el estado del registro MSTATUS (que es un registro especial para manejar interrupciones), lo que hace `csrrs zero, 5, t0` es escribir, a partir del  bit 5, el valor de `t0` en MSTATUS. Las istrucciones `csrrsi` son similares, pero en lugar de escribir los contenidos del registro que se pasa como `rs1` en `csrrs`, reciben un unsigned int de a los más 5 bits, lo cero-extienden `csr` bits (como la instrucción anterior) y escriben los bits high en MSTATUS, por lo que al final lo que hace es escribir `1` en el bit 4 de MASTATUS y la útlima instrucción escribe 1 en el bit 0 de MSTATUS. 

Esta secuencia de instrucciones le indica al procesador que las interrupciones están activadas, y que en caso de ocurrir una interrupción, debe ejecutar el código presente en la dirección `handle` hasta llegar a la instrucción `uret`.

Si quieres leer más, puedes revisar el capítulo 7 del manual que subimos junto con el emulador y el capítulo 2.8 de [este documento](https://riscv.org/wp-content/uploads/2017/05/riscv-spec-v2.2.pdf).

**Comment by JuanDlugo** [comment]
Buenísimo. Mil gracias nuevamente!

**Comment by ElKrra** [comment]
@tocococa y qué es lo que hace la instrucción `uret`? En el emulador aparece que se encarga de volver del manejo de alguna excepción o interrupción a `uepc` pero he podido encontrar cómo lo hace (si sigue directamente con la línea que sigue o salta hacia la dirección de memoria almacenada en un registro). Al intentar quitar las líneas de loops de `interrupts.asm` el programa termina en error, por lo que no he podido descubrir cómo lo hace.

**Comment by tocococa** [comment]
Hola @ElKrra, la instrucción `uret` viene de "unconditional return" y se usa para retornar de traps generados en modo U, que es justamente lo que hace la interrupción del timertool.

Las líneas del loop son solamente para dejar al programa en una suerte de "busy waiting" mientras espera a la interrupción, en un programa real podría estar haciendo otras cosas y se interrumpido en cualquier momento.

**Comment by ElKrra** [comment]
@tocococa Claro, entiendo, pero no me queda claro a qué dirección es a la que se retorna con `uret` o si se puede especificar un label de retorno. Me pasa que mi código funciona correctamente pero no he podido hacer que luego de contar los segundos el programa vuelva a un label específico para poder seguir ejecutándose. Aparentemente se queda pegado manejando la excepción y si intento realizar una instrucción de tipo jump antes de llegar a `uret` entonces el timer queda desconfigurado y no funciona correctamente.

**Comment by tocococa** [comment]
@ElKrra , la subrutina que maneja la interrupción NO modifica el program counter (PC) del script principal, esta utiliza un contador especial que en RISC-V se llama `uepc`, de User Exception PC. La instrucción `uret` es parte de la extensión que incluye interrupciones, y lo que hace es retornar la ejecución a la intrucción que estaba en el PC el momento en que se gatilló la interrupción, y como `j` y los demás saltos son instrucciones que dependen del PC, no debieses utilizarlos dentro de la interrupción.

**Comment by ElKrra** [comment]
Buenísimo! Me solucionaste el problema, gracias!
