### ISSUE TITLE
[T2-P1] Respuesta única a los tests 

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2343/Syllabus-2021-2-S1#45]
**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**
Hola!, estaba revisando los tests y me surgió una duda, ya que me parece que pueden existir varios outputs válidos frente a los gastos que se entregan. Por ejemplo, en el primer ejemplo de los tests, la solución es:

> 0 debe pagar 10200.0 a 3
> 2 debe pagar 3600.0 a 3
> 2 debe pagar 6600.0 a 4
> 1 debe pagar 2200.0 a 4
> 
> 

Y la solución que obtuve yo fue:

> 0 debe pagar 10200 a 3
> 2 debe pagar 8800 a 4
> 1 debe pagar 2200 a 3
> 2 debe pagar 1400 a 3
> 

Que es equivalente en términos del balance final.
Esta respuesta se considerará buena también?
Muchas gracias!

**Comment by rbhernandez** [comment]
Hola! sí, es correcto también. Hay que preocuparse de que los montos coincidan los de los test y que se mantenga la cantidad de transacciones 😄

**Comment by Francisco5674** [comment]
Hola! 
Llevo mucho tiempo en esto, y por fin tengo un output aceptable, sin embargo, en ocasiones me da una transacción adicional, pero que sin embargo todos tienen que pagar lo mismo de todas, y los que reciben, también reciben siempre lo mismo. Por ejemplo:

Mi solución es:
  2 debe a 3
  5200.0
  1 debe a 3
  2000.0
  0 debe a 3
  6600.0
  0 debe a 4
  3600.0
  2 debe a 4
  5000.0
  1 debe a 4
  200.0
