### ISSUE TITLE
Error de tipeo Test 3

### ISSUE THREAD

**Issue by NicolasLahsen** [IIC2343/Syllabus-2021-2-S1#48]
**¡¡Quejas y reclamos vía mail a `iic2343@ing.puc.cl` o a `yadran@ing.puc.cl`!!**
Hola! En el test 3, el primer gasto es de 3000.9, y debiera ser de 3000.0 para que de el resultado correcto.
Saludos!

**Comment by rbhernandez** [comment]
Sí, todos los floats deben ir con un `.0` efectivamente es un error de tipeo, gracias por notarlo!
