### ISSUE TITLE
P2 incio Timertool

### ISSUE THREAD

**Issue by Mario-uc** [IIC2343/Syllabus-2021-2-S1#49]
**Quejas y reclamos vía mail a `iic2343@ing.puc.cl`.**
Una consulta , hay algún comando para reiniciar el timer tool sin yo tener que apretar el botón? y para que ponga play también existe alguno?

**Comment by tocococa** [comment]
Hola @Mario-uc. no que yo sepa, tienes que iniciarlo todo a mano.
