### ISSUE TITLE
Solicitud cambio de fecha T2

### ISSUE THREAD

**Issue by itplanella** [IIC2343/Syllabus-2021-2-S1#50]
Hola!

Esperando que estén teniendo una buena semana, escribo para solicitar si es posible que se extienda el plazo para la tarea 2. Esto lo solicito ya que existen muchos ramos de computación que tienen entregas para estos días y podrían haber varios alumnos en esta situación, por lo que dar más plazo nos ayudarían en primer lugar a entregar una mejor tarea y en segundo lugar a no sufrir tanto estrés, ya que esta tarea vale el 20% del ramo. 
A continuación dejo las fechas de varias evaluaciones que tengo estos días, si pudieran conversar al respecto y considerarlo lo agradecería mucho :)

Jueves 04: Tarea 2 EDD
Viernes 05: Entrega 2 Software - Entrega 1 Minería de datos
Lunes 08: I2 EDD
Martes 09: I2 Software -**Tarea 2 arquitectura de computadores**

**Comment by juansegmart** [comment]
Up

**Comment by tpcarrasco** [comment]
Me sumo a lo anterior! Agrego también que el miércoles 10 hay interrogación de Matemáticas Discretas del DCC.

**Comment by Gsalinas1506** [comment]
Me sumo a la petición. Como extra, el Jueves 11 hay entrega de Hito de Visualización de Información (IIC2026)

**Comment by galanfd** [comment]
Me sumo! Agrego que el Jueves 11 también está la i2 de Finanzas

**Comment by tocococa** [comment]
Hola! Entiendo la situación y personalmente no tengo demasiado atado en darles más plazo, mi única preocupación es que, si les damos más plazo, la entrega de la tarea 2 estaría quedando a apenas un par de días de la I2 y no se si les complicaría mucho eso. Quedo atento a sus comentarios!

**Comment by Gsalinas1506** [comment]
Personalmente, es un riesgo que estoy dispuesto a aceptar

**Comment by itplanella** [comment]
igualmente estoy dispuesto a aceptar el riesgo, prefiero poder repartir mi carga académica en mas días si es posible

**Comment by Mario-uc** [comment]
Lo mismo que dijo la persona de arriba uwu
