### ISSUE TITLE
Duda ejemplo interrupts

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2343/Syllabus-2021-2-S1#51]
Hola me surge la duda de porque al armar el timer se guarda la configuración en a0 y a1 pero al rearmar se utiliza t0 y t1?
gracias de antemano

**Comment by tocococa** [comment]
Hola, eso da un poco lo mismo, porque en realidad se está guardando a la dirección a la que apunta el label `cmp`, el delta para el timer es revisado por el timertool desde esa dirección y no desde un registro.

**Comment by JuaniAndres** [comment]
perfecto entiendo gracias
