### ISSUE TITLE
Timer T2

### ISSUE THREAD

**Issue by emena97** [IIC2343/Syllabus-2021-2-S1#52]
Hola, estaba haciendo la parte 2 de la tarea, y me di cuenta que el timer no empieza a correr cuando se corre el programa, sino que se debe correr por separado. Entonces puede pasar que si yo corro el timer y lo dejo correr un rato y luego pongo mi input (digamos 10 s) estos segundos ya van a haber pasado y va a saltar la interrupción altiro. Entonces como se maneja esto y como se van a correr las cosas al momento de corregir?

Gracias!

**Comment by tocococa** [comment]
Hola @emena97, para el timer, lo que puedes hacer es leer el tiempo actual y luego calcular la diferencia de segundos que necesitas hasta que el timer se dispare, usando el tiempo que recibes como input. En el ejemplo que subí con la ayudantía de la tarea 2 se hace eso cuando se rearma el timer.

**Comment by emena97** [comment]
Perfecto, gracias!
Y para efectos de la corrección se asume que se inicia el timer y luego se corre el programa?

**Comment by tocococa** [comment]
Si, probablemente sea así.
