### ISSUE TITLE
Duda output Tarea 2 parte 1

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2343/Syllabus-2021-2-S1#55]
Hola, una duda el output tiene que seguir algún orden o da lo mismo el orden en que entregue quien le debe a quien?
Gracias de antemano

**Comment by tocococa** [comment]
Hola @JuaniAndres, no hay problema en que salgan desordenados mientras el resultado sea el correcto.

**Comment by JuaniAndres** [comment]
Perfecto gracias

**Comment by Francisco5674** [comment]
Hola!, sobre la misma idea, aunque el enunciado no dice nada al respecto, mi output suele tener más transacciones de salida que las que tienen los test cases, sin embargo, jamás ocurre que "i" le deba a "j" y "j" le debe a "z", por ejemplo. Además comparando con los outputs de los test cases, el balance es exactamente el mismo. 

El output esperado del primer caso es:
  0 debe pagar 10200.0 a 3
  2 debe pagar 3600.0 a 3
  2 debe pagar 6600.0 a 4
  1 debe pagar 2200.0 a 4

Mientras que el mío es: 

  2 debe a 3
  5200.0
  1 debe a 3
  2000.0
  0 debe a 3
  6600.0
  0 debe a 4
  3600.0
  2 debe a 4
  5000.0
  1 debe a 4
  200.0

Sin embargo, ambas expresiones son equivalentes, supongo que esta bien, ¿verdad?

**Comment by juanicortesl** [comment]
Me sumo a la duda de @Francisco5674 . Obtengo outputs distintos a los de los test cases, pero son equivalentes, ya que cada persona tiene que pagar y/o recibir el mismo monto total que en los ejemplos

**Comment by rbhernandez** [comment]
Hola, la verdad es que  cuando más de una combinación es acertada, es porque tienen la misma cantidad de transacciones. El output del test son 4 transacciones, entonces si el output que te arroja son 6 transacciones, no está del todo correcto. El programa no está siendo eficiente, quizás porque están haciendo el ajuste de cuentas por cada deuda, y no por la deuda total.

**Comment by jdlarrain** [comment]
En mi caso hago el ajuste con la deuda total y me dan outputs distintos al test pero que tienen sentido. Si a la hora del ajuste recorro la lista de deudas en una dirección me da un output distinto que si lo hago en la dirección opuesta, por ejemplo.

**Comment by rbhernandez** [comment]
La idea de la tarea era que funcionara de forma eficiente, no tiene sentido que se hagan demasiadas transacciones para saldar las deudas. Mientras más cercano al output, mejor está la eficiencia del código. 
Ahora, como no se especificó en el enunciado que debía ser eficiente, se considerarán buenos aquellos outputs que distribuyan bien la deuda (montos correctos) y que no tengan líneas del tipo "A debe a B y B debe a C", pues lo correcto es que "A debe a C" y eso si está en el enunciado.

**Comment by fbarrosalcalde** [comment]
Hola, en la parte 1 de la tarea, darán puntaje si es que no llego al output que se pide en el enunciado, pero si entrego un avance? (por ejemplo mostrar el saldo final de cada amigo)
