### ISSUE TITLE
Diferencia entre usar sp o gp

### ISSUE THREAD

**Issue by vnespinosa** [IIC2343/Syllabus-2021-2-S1#56]
Hola, quería preguntar qué diferencia hay entre usar `gp` o `sp` para guardar datos, en qué caso es correcto usar cada uno? y en el contexto de la T2-P1, cuál debería usar?

Gracias

**Comment by tocococa** [comment]
Hola @vnespinosa, el registro `gp` corresponde al Global Pointer y está reservado para mantener un puntero al área estática (el principio de la memoria asignada al programa), por lo que no lo debieses modificar. Si tienes que almacenar datos puedes usar el stack (a donde apunta `sp`), que se debiese comportar como una cola LIFO. Si necesitas una cantidad variable de espacio y además poder acceder a cualquiera de ellos en cualquier momento, deberías utilizar las direcciones a continuación del último dato en la sección `.data`, ya que esa sección corresponde al heap.
