### ISSUE TITLE
T2 P1 .data

### ISSUE THREAD

**Issue by IgnacioPorte** [IIC2343/Syllabus-2021-2-S1#57]
Holaaa qué tal, tengo una duda respecto a la tarea.  En .data puedo definir otros labels aparte de los que nos dicen en el enunciado, como por ejemplo 'array' en la imagen?
![image](https://user-images.githubusercontent.com/62029630/140561814-b13872d9-b26a-45d0-8927-e7a8b252324f.png)

**Comment by tocococa** [comment]
Hola @IgnacioPorte, sep, no hay problema en que hagan eso, mientras no utilices los labels `N, amigues, G, gastos` para una cosa diferente.

**Comment by IgnacioPorte** [comment]
Perfect, graciass

**Comment by mgbriones** [comment]
despues de cargados los label N, amigues, G, y gastos es posible modificar sus valores durante la ejecucion?

**Comment by tocococa** [comment]
@mgbriones. si, ningún problema con eso mientras llegues a una solución correcta.
