### ISSUE TITLE
T2 P1 print floats

### ISSUE THREAD

**Issue by jperalta2202** [IIC2343/Syllabus-2021-2-S1#58]
Hola, estoy teniendo problemas con lo siguente. En la ayudantia se nos mostro una manera de imprimir floats, que utiliza una funcion terminator que accede a una variable en .data que se llama null y que debe estar al final. Pero tambien estoy implementando un arreglo de largo variable utilizando una variable en .data que tambien debe estar al final. Como puedo imprimir floats de otra manera? sin necesitar el terminator

**Comment by Francisco5674** [comment]
Compa use el syscall de PrintFloat nomas, al menos así lo hago yo:

![image](https://user-images.githubusercontent.com/61996440/140610725-ce258794-2e45-47cf-8d97-b391b6e743fa.png)

**Comment by jperalta2202** [comment]
Gracias! eso me funciono
