### ISSUE TITLE
Duda sobre los saved registers

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2343/Syllabus-2021-2-S1#59]
Hola, me surge la duda bajo la convención en que contexto se ocupan los saved registers?. Estuve investigando pero no me quedo muy claro con lo que encontré.

**Comment by tocococa** [comment]
Hola @JuaniAndres, la particularidad de los registros `s*` es que en caso de haber una llamada a una subrutina, se debe garantizar que al volver a la sección principal, el valor de dichos registros sea el mismo que tenían al inicio de la llamada.

**Comment by JuaniAndres** [comment]
Entiendo pero es necesario utilizarlos bajo el contexto de subrutina o por ejemplo si uno trabaja solo en la sección principal los puede utilizar para guardar información?

**Comment by tocococa** [comment]
Puedes usarlos en cualquiera de los dos contextos, lo importante es que si la subrutina usa algún registro `s`, esta se tiene que asegurar que en el momento que la subrutina termine y continúe la ejecución de la sección principal, los valores de todos los registros `s` que utilizó la subrutina sean los mismos que habían justo antes del llamado de la subrutina. Por ejemplo, si tu subrutina tiene que usar los registros `s0-3` con valores `a,b,c`, al inicio de la subrutina guardas sus valores en el stack, y antes de retornar a la sección principal, la subrutina restablece los valores de `s0-3`, que ahora podrían ser `x,y,z`, a los valores que dejó en el stack para ellos, así ahora los valores de `s0-3` vuelven a ser `a,b,c`, de manera similar a como se respaldan los registros en el ejemplo de la interrupción que subimos en la ayudantía.

**Comment by JuaniAndres** [comment]
Perfecto me quedo clarísimo muchas gracias @tocococa
