### ISSUE TITLE
Duda formato entrega tarea 2

### ISSUE THREAD

**Issue by jncaceres** [IIC2343/Syllabus-2021-2-S1#60]
Hola, me surgió una duda con el formato de entrega de la tarea ya que en el enunciado dice que son en un .txt pero en el cuestionario de siding dice .asm, entonces no se que en formato entregarlas.

Muchas gracias de antemano!

**Comment by rbhernandez** [comment]
Hola! hubo un pequeño error en el formulario, debe entregarse en `.txt`. Igualmente, para quienes ya entregaron, aceptaremos si entregaron en `.txt `o `.asm`

**Comment by jncaceres** [comment]
Muchas gracias!
