### ISSUE TITLE
Problema aritmetica entre floats

### ISSUE THREAD

**Issue by camaruri** [IIC2343/Syllabus-2021-2-S1#61]
Tengo un problema al tratar de sumar o restar entre dos floats.
tengo en un registro fa5 un numero que tiene que ser restado a fa6 y sumado a fa7.
Los valores en los registros de floating point son:
fa5: 10200.0
fa6: -10200.0
fa7: 13.800.0
Pero al sumar y restar con las instrucciones fadd.s y fsub.s el resultado es NaN.
No he podido saber porque se produce ese valor NaN.
Muchas gracias.

**Comment by tocococa** [comment]
Hola @camaruri. hice un script que repite las intrucciones que describiste tú y no me entrega NaN como resultado, me entrega  -6600.0 que es el resultado de hacer (fa6-fa5)+fa7, así que el error tiene que ser en otra parte.

**Comment by camaruri** [comment]
Buena muchas gracias! si el error era en otra parte!
