### ISSUE TITLE
T2 - Problemas al cargar gasto (G)

### ISSUE THREAD

**Issue by mgbriones** [IIC2343/Syllabus-2021-2-S1#62]
Hola en mi programa algo curioso ocurre cuando hago una segunda iteracion del loop, y es que al querer cargar G en el registro t2, este anota  -1082130432, lo que claramente es un error. ¿Que es lo que podria estar pasando?

![image](https://user-images.githubusercontent.com/53794443/140822409-b22e5587-a06a-43a6-95e5-9c830b4d6d50.png)

![image](https://user-images.githubusercontent.com/53794443/140822473-accd1cbd-3762-4a00-8381-bb808c7ebd3f.png)

**Comment by MarceloSaldias** [comment]
Primero tienes que cargar la dirección de memoria de G en un registro, y despues cargar a un registro el contenido de esa dirección de memoria
```
la t0, G # t0 = dir(G)
lw t1, 0(t0)  # t1 = G
```

**Comment by mgbriones** [comment]
Cual es la diferencia con cargar directamente con lw? El emulador también me deja hacerlo
`lw t1, G`
