### ISSUE TITLE
T1 P1 Largo de los floats al imprimir

### ISSUE THREAD

**Issue by jperalta2202** [IIC2343/Syllabus-2021-2-S1#64]
Hola, tengo una duda respecto al largo que deben tener los floats al momento de imprimir el output. 

Mi codigo esta imprimiendo un float de la siguiente manera: "0 debe pagar 8517.857 a 4" pero en las soluciones de los test ese output aparece como: "0 debe pagar 8517.857142857143 a 4". Yo en ningun momento opero con los floats aproximandolos a ints, entonces no se si mi output estara correcto

**Comment by rbhernandez** [comment]
hola, sí está correcto :)

**Comment by jperalta2202** [comment]
gracias!
