### ISSUE TITLE
Duda corrección Tarea 2, parte 1

### ISSUE THREAD

**Issue by fbarrosalcalde** [IIC2343/Syllabus-2021-2-S1#65]
Hola, en la parte 1 de la tarea, darán puntaje si es que no llego al output del enunciado, pero sí entrego un avance? (por ejemplo, mostrar el saldo final de cada amigo). Gracias!

**Comment by rbhernandez** [comment]
Hola, la corrección de la tarea tiene otros ítems aparte de los tests, por lo que sí podrias tener puntaje en otras secciones. Si tus resultados no son los esperados, entonces tendrás 0 puntos en los tests.

**Comment by fbarrosalcalde** [comment]
Perfecto, gracias!
