### ISSUE TITLE
Duda sobre el Test 3 de la T2P1

### ISSUE THREAD

**Issue by JuaniAndres** [IIC2343/Syllabus-2021-2-S1#66]
Hola me surge la duda si ese test esta correcto ya que creo que falta que 2 le deba 1 por el segundo gasto. También los montos de los outputs me parecen raros porque en el gasto 1 la persona 1 le debe 10000,3 a 0 luego en el gasto 2 la persona 0 le debe 5166,667 a la persona 1 lo cual si restamos el segundo numero al primero resulta en total 4833,633 que le debería deber 1 a 0. No se si cometí algún error en ese calculo o algo que no este considerando?

**Comment by rbhernandez** [comment]
Hola @JuaniAndres! el resultado de ese test está correcto

**Comment by JuaniAndres** [comment]
Hola @rbhernandez en que me equivoque en mi lógica que no me hace mucho sentido los números de la respuesta

**Comment by rbhernandez** [comment]
```
3) 

Input

N: 3
amigues: 0, 1, 2
G:3
gastos: 0.0, 30000.9, -1.0, 1.0, 15500.0, -1.0, 2.0, 2370.0, -1.0

--------------------------------------------------------------------------------------

Output

2 debe pagar 13586.666666666668 a 0

1 debe pagar 456.66666666666424 a 0
```

Primer gasto:
1 debe 10000,3 a 0
2 debe 10000,3 a 0
Segundo gasto:
1 debe 4834,3 a 0
2 debe 10000,3 a 0 y 5166 a 1
En el tercer gasto 0 y 1 deben pagar 790 a 2, por lo tanto:
2 debe 10000,3 - 790 = 9210,3  a 0 y 5166 - 790  =  4376‬ a 1

Entonces, finalmente:
>> Como 2 debe 4376‬ a 1 y 1 debe 4834,3 a 0 entonces, traspasamos la deuda de 1 a 2, quedando asi:
>> 2 debe 4376 + 9210,3 = `13586 a 0` y 1 debe 4834,3 - 4376 = `458,3 a 0 `

**Comment by JuaniAndres** [comment]
Ahora entiendo que aparte de repartir los gastos había que realizar la menor cantidad de transacciones 
Muchas gracias por la explicación
Una ultima duda si no realizamos esa optimización igual recibiríamos algún puntaje parcial considerando que se reparten bien las deudas pero no en la menor cantidad de transacciones?

**Comment by rbhernandez** [comment]
la issue #65 puede resolver esa duda 😄
