### ISSUE TITLE
T2- sobre exactitud de las respuestas p1

### ISSUE THREAD

**Issue by mgbriones** [IIC2343/Syllabus-2021-2-S1#67]
Que tan exacta deben ser las respuestas de la parte 1? en mi caso la parte entera de las respuestas me da igual que los ejemplos, pero la parte decimal cambia. Asumo que debe ser por algun redondeo o algo, pero es necesario que sea idéntica la respuesta a los ejemplo?

si las respuestas de los ejemplos son : 13586.666666666668 y  456.66666666666424, las mias son 13586.967 y 456.9668.

saludos!

**Comment by rbhernandez** [comment]
Hola, está bien, revisa la issue #64.

**Comment by mgbriones** [comment]
gracias!
