### ISSUE TITLE
T2-P1: Asignar manualmente una dirección de memoria a una variable declarada

### ISSUE THREAD

**Issue by tcouso** [IIC2343/Syllabus-2021-2-S1#68]
Hola!

Tengo un problema con respecto al almacenamiento de arreglos en la Parte 1 de la Tarea 2. Necesito implementar tres arreglos cuyo largo sea la cantidad de amigos de un testcase. El problema es que si inicializo las tres variables vacías, todas quedan en la misma dirección de memoria, de modo que se sobrescriben mutuamente al modificarlas. Pensaba que para solucionar esto era necesario settear manualmente la direcciones de almacenamiento, de modo que todas queden trasladadas mutuamente según un offset igual al largo de los arreglos, pero no he logrado encontrar una forma de hacer eso, de modo que cualquier ayuda es muy bienvenida :)

Saludos, y gracias de antemano!

**Comment by tocococa** [comment]
Hola, puedes usar la directiva `.space n` para dejar n bytes libres entre direcciones en la sección data.

**Comment by tcouso** [comment]
Buenísima, y el valor `n` tiene que ser necesariamente un literal? O puede ser un valor cargado a un registro?

**Comment by tocococa** [comment]
Como es algo que tu defines en la sección data, que es estática, tiene que ser un valor que tu le pasas de antemano, si necesitas un arreglo de largo variable, tienes que usar el heap, que corresponde a las direcciones a partir del último valor declarado en la sección data, entonces podrías usar `.space` para dejar espacio para 3 direcciones y 3 largos en la sección estática, y con eso vas guardando y accediendo a los arreglos en el heap.
