### ISSUE TITLE
Duda Test 2

### ISSUE THREAD

**Issue by galanfd** [IIC2343/Syllabus-2021-2-S1#69]
Hola! Estaba revisando los gastos de cada test y me di cuenta de que cuando se indica el número X de personas que participan en el gasto, cuando no es -1, en el Test 2 en varios casos no se incluye el que paga dentro de los X que pagan, mientras que en el test 1 siempre sí. 
¿Se supone que esto es así o estoy viendo algo mal yo?
De antemano muchas gracias!!!
Edit: También vi que faltan comas si no me equivoco en el último gasto

**Comment by rbhernandez** [comment]
Hola! los gastos indican el número X de personas que participan en el gasto y estas pueden o no incluir a la persona que pagó. Si en ningún gasto del test, hay gastos con X distinto a -1 y no participa quien pagó, es solo coincidencia.

**Comment by galanfd** [comment]
Ah perfecto entiendo. ¡Muchísimas Gracias!!
