### ISSUE TITLE
T2 P2 Maximo tiempo a recibir

### ISSUE THREAD

**Issue by tomascortes** [IIC2343/Syllabus-2021-2-S1#71]
Hola, tengo la duda de si para la parte 2 tenemos que considerar que puede llegar un numero más grande a 32 bits?

**Comment by tomascortes** [comment]
En realidad mayor a 4294967
(para ver si se tiene que manjear un numero más grande de 32 bits al final)

**Comment by tocococa** [comment]
Hola @tomascortes, no vamos a pedirles un número tan grande, no te preocupes por eso, si no no acabaríamos nunca de esperar.
