### ISSUE TITLE
T2- duda enunciado p2

### ISSUE THREAD

**Issue by mgbriones** [IIC2343/Syllabus-2021-2-S1#72]
Hola me genera una duda esta parte del enunciado:

![image](https://user-images.githubusercontent.com/53794443/141472892-2f08dac0-89b3-4e9f-ada1-dde731e163f2.png)

quiere decir esto que el codigo de la ecall no puede estar al final del codigo?

**Comment by fmitjans** [comment]
Hola, no soy ayudante, pero lo que entendí es que el programa no puede terminar porque se le acabó el código. Si haces un programa de ejemplo con pocas lienas, puedes ver en la terminal que termina con: 
-- program is finished running (dropped off bottom) --
Para que no pase esto puedes usar el ecall 10 al final de tu codigo, que entrega
-- program is finished running (0) --

**Comment by tocococa** [comment]
Hola @mgbriones, es exactamente lo que dijo @fmitjans!
