### ISSUE TITLE
Problema parte 1 tarea 1

### ISSUE THREAD

**Issue by martinrtc** [IIC2343/Syllabus-2021-2-S1#73]
Estoy teniendo un problema al crear los strings para los output de la parte 1
<img width="773" alt="Captura de Pantalla 2021-11-12 a la(s) 18 32 21" src="https://user-images.githubusercontent.com/53836754/141537078-0ebabda0-6f5e-4cb5-98df-912848e31ad5.png">

Asi como muestra la imagen. Me esta sucediendo que al crear ese string, me esta cambiando el arreglo gastos no se porque, me lo desordena al parecer como si fuera un overflow de memoria. 

<img width="494" alt="Captura de Pantalla 2021-11-12 a la(s) 18 34 18" src="https://user-images.githubusercontent.com/53836754/141537274-ea9839fe-5d43-4869-91b1-ece90d4484fc.png">

Ese es mi output del primer test sin crear el string, si lo miran bien esta correcto, solo faltaría imprimir los strings y que se vea ordenado. 
Mi output al crear el string es el siguiente: 

<img width="597" alt="Captura de Pantalla 2021-11-12 a la(s) 18 35 37" src="https://user-images.githubusercontent.com/53836754/141537410-65097c9c-78ed-4a32-9fb3-89dc5b570427.png">

El unico cambio que hice fue crear el string, nada más, y me arroja un output distinto. 

Al parecer es un error de memoria o algo por el estilo pero no he podido arreglarlo.

**Comment by tocococa** [comment]
Hola @martinrtc, no se a que string te refieres con "ese string", pero `R:` y `debe:` se te están guardando en la misma dirección de memoria porque no hay nada entre ellos, revisa las issues #56 y #68 en que se habla de como solucionarlo. Si lo que se te imprime mal es algo de arriba, te recomiendo usar la directiva `.asciiz` en vez de `.ascii`.
