### ISSUE TITLE
Duda modalidad I2

### ISSUE THREAD

**Issue by BcruzUC** [IIC2343/Syllabus-2021-2-S1#77]
Hola !

¿La modalidad de la I2 será igual a la de la I1? Traté de buscar información de eso, pero no encontré.
Estoy trabajando y no puedo asistir a las clases, luego estudio de los ppt, por lo que si se dijo en alguna clase no lo escuché.
Sé que debería haber visto las clases y así saber, pero si me pueden ayudar a asegurarme que será igual a la I1, se los agradecería :)

Saludos!

**Comment by tocococa** [comment]
Hola @BcruzUC, el formate de la I2 es similar a la I2, son 4 preguntas y responden 3, de 8:30 a 21:00, con horario de consultas a las 8:30 y a las 19:00.

**Comment by BcruzUC** [comment]
Muchas gracias !!
