### ISSUE TITLE
DUDAS I2

### ISSUE THREAD

**Issue by AndresGonzalez5** [IIC2343/Syllabus-2021-2-S1#79]
Estas son las preguntas que surgieron en la primera ronda de consultas:
Link a la grabación de la primera sesión: PENDIENTE

## **Preguntas Generales:**
- Se sube a SIDING en el cuestionario respectivo a cada pregunta
- Justifiquen sus respuestas, ya que el desarrollo es lo más importante
- Cada subpregunta vale lo mismo

## **Pregunta 1:**
- Pregunta a.i y la pregunta a.ii son dos preguntas independientes
- Pregunta a.i el tiempo efectivo de acceso es lo mismo que tiempo promedio de acceso
- Pregunta b las 4000 entradas son líneas de la caché
- Pregunta a tiempo de 1 microsegundo hace referencia a la memoria RAM

## **Pregunta 2:**
- Tabla de página y TLB son cosas distintas
- Cuando se dice que hay espacio para que todo quepa correctamente, significa que hay espacio para todas las direcciones. La tabla de paginas almacena todas las paginas que se necesitan con su metadata.
- Si se pueden pasar las direcciones de hexadecimal a binario y trabajar con eso

## **Pregunta 3:**
- Los 10ns de la etapa IF están contemplados dentro de los tiempos de ejecución de las instrucciones mencionadas (e.j. si se demora 30ns en ejecutar la instrucción, entonces 20ns se demoran las etapas que no son el IF)
- Que no haya predicción de saltos significa que el computador se percata del salto cuando llega a la etapa de ejecutarse el salto
- Pregunta b el computador con pipelining cuenta con forwarding units

## **Pregunta 4:**
- El assembly es el de Assembly básico (NO RISC-V)

**Comment by crvargasu** [comment]
En la P2, la TLB parte vacía?

**Comment by NicolasLahsen** [comment]
En la P1 b ii, consideramos que la caché no almacena un bit de validez?

**Comment by mframos3** [comment]
En la P2, están bien los tamaños de las memorias y páginas en relación a la cantidad de bits de dirección de memoria virtual? 12 bits para direcciones no son suficientes para 4MB de espacio virtual.

**Comment by JuaniAndres** [comment]
Solo confirmar en la pregunta 4 con indicar los valores finales se refiere a decir X vale tanto, Arr[0] vale tanto ...?

**Comment by Sadhguy** [comment]
En la pregunta 2 podemos asumir que está toda la memoria física libre inicialmente?

**Comment by jitorralba** [comment]
> Solo confirmar en la pregunta 4 parte b con indicar los valores finales se refiere a decir X vale tanto, Arr[0] vale tanto ...? En la misma parte la tabla se rellena en base al código de la parte a o hay que trabajarlo como una tabla de instrucciones en base a lo que dice el enunciado similar al ejercicio de la ayudantía antepasada?

Me sumo a esta pregunta, como se nos pide hacer el código podríamos usar otros registros, y por consiguiente rellenar la parte b en base a eso?

**Comment by JuaniAndres** [comment]
Hola en la pregunta 1 a el tiempo de acceso a la memoria no debería ser mayor al tiempo de acceso al cache?

**Comment by tlagosh** [comment]
Hola, estaba haciendo la prueba en Latex y se acaba de caer overleaf. No estoy seguro de cuándo va a volver pero tenía todo mi avance ahí. Alguna recomendación de qué se puede hacer? Por ahora no puedo ni siquiera acceder al proyecto para ver lo que tenía y pasarlo a otra parte.

**Comment by cabendek** [comment]
En la pregunta 3, se puede asumir que el Instruction Fetch es la etapa que más demora en todas las instrucciones?

**Comment by JuaniAndres** [comment]
Hola para la  pregunta 1bii es necesario considerar un bit de validación?

**Comment by MarceloSaldias** [comment]
En la P3, no existen problemas con el computador que se considera para el pipelining para ejecutar la instrucción ADD A, (var2) ? Podemos cambiar esta instruccion por otras que tengan el mismo resultado pero no tengan problemas en el pipelining?

**Comment by fran-gl** [comment]
> Hola para la pregunta 1bii es necesario considerar un bit de validación?

Me sumo a esta pregunta. Además, ¿tenemos que considerar un dirty bit?

**Comment by sufigueroa** [comment]
> En la P2, la TLB parte vacía?

Sip



> En la P2, están bien los tamaños de las memorias y páginas en relación a la cantidad de bits de dirección de memoria virtual? 12 bits para direcciones no son suficientes para 4MB de espacio virtual.

Las entradas pueden ser mayores a un byte



> En la pregunta 2 podemos asumir que está toda la memoria física libre inicialmente?

Sip, parte vacia

**Comment by jiurrutia** [comment]
> > En la P2, la TLB parte vacía?
> 
> Sip
> 
> > En la P2, están bien los tamaños de las memorias y páginas en relación a la cantidad de bits de dirección de memoria virtual? 12 bits para direcciones no son suficientes para 4MB de espacio virtual.
> 
> Las entradas pueden ser mayores a un byte
> 
> > En la pregunta 2 podemos asumir que está toda la memoria física libre inicialmente?
> 
> Sip, parte vacia

Yo tengo la misma duda. Si las direcciones son de 12 bits entonces el espacio direccionable seria menor al tamaño de cada pagina (256KB)

**Comment by mgbriones** [comment]
P4- no deberia una sola forma de hacer este codigo, por lo que puedo asumir que no todas las tablas deben ser iguales?

**Comment by Niko12121** [comment]
> > > En la P2, la TLB parte vacía?
> > 
> > Sip
> > 
> > > En la P2, están bien los tamaños de las memorias y páginas en relación a la cantidad de bits de dirección de memoria virtual? 12 bits para direcciones no son suficientes para 4MB de espacio virtual.
> > 
> > Las entradas pueden ser mayores a un byte
> > 
> > > En la pregunta 2 podemos asumir que está toda la memoria física libre inicialmente?
> > 
> > Sip, parte vacia
> 
> Yo tengo la misma duda. Si las direcciones son de 12 bits entonces el espacio direccionable seria menor al tamaño de cada pagina (256KB)

Me sumo a la duda
